# Generated by Django 4.1.7 on 2023-04-17 07:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Employer", models.CharField(max_length=50)),
                ("Title", models.CharField(max_length=50)),
                (
                    "Sector",
                    models.CharField(
                        choices=[
                            ("Self-employed", "Self-employed"),
                            ("Retail Trade", "Retail Trade"),
                            ("Construction", "Construction"),
                            ("Agriculture", "Agriculture"),
                            ("Manufacturing", "Manufacturing"),
                            ("Wholesale Trade", "Wholesale Trade"),
                            ("Finance and Insurance", "Finance and Insurance"),
                            ("Education and Training", "Education and Training"),
                            (
                                "Transportation and Warehousing",
                                "Transportation and Warehousing",
                            ),
                            (
                                "Accommodation and Food Services",
                                "Accommodation and Food Services",
                            ),
                            (
                                "Healthcare and Social Assistance",
                                "Healthcare and Social Assistance",
                            ),
                            (
                                "Professional, Scientific, and Technical Services",
                                "Professional, Scientific, and Technical Services",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Contract_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contract", "Fixed-term Contract"),
                            ("Freelance Contract", "Freelance Contract"),
                            ("Self-employed", "Self-employed"),
                        ],
                        max_length=80,
                    ),
                ),
                ("Date", models.DateField(default=datetime.date.today)),
                ("Current_employment", models.BooleanField(default=False)),
                (
                    "employment_infor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "score_infor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Credit_cards",
                    models.CharField(
                        choices=[
                            ("0", "I have never had a credit card"),
                            ("1", "Only 1"),
                            ("2", "2 to 3"),
                            ("3", "4 to 6"),
                            ("4", "5 or more"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Overdue_accounts", models.PositiveIntegerField()),
                (
                    "Deliquency",
                    models.CharField(
                        choices=[
                            ("0", "None"),
                            ("1", "30 days deliquent"),
                            ("2", "60 days deliquent"),
                            ("3", "90 days deliquent"),
                            ("4", "More than 90 days deliquent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Missed_payments",
                    models.CharField(
                        choices=[
                            ("0", "I have never missed a payment"),
                            ("1", "In the past 3 months"),
                            ("2", "3 to 6 months ago"),
                            ("3", "6 months to 1 year ago"),
                            ("4", "1 to 2 years ago"),
                            ("5", "2 to 4 years ago"),
                            ("6", "more than 4 years ago"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Credit_balances",
                    models.CharField(
                        choices=[
                            ("0", "I only have mortgage loan(s)"),
                            ("1", "Less than $500"),
                            ("2", "$500 to $999"),
                            ("3", "$1000 to $4,999"),
                            ("4", "$5000 to $9,999"),
                            ("5", "$10,000+"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Loan_applications",
                    models.CharField(
                        choices=[
                            ("0", "None"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3 to 5"),
                            ("4", "6 or more"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "First_loan",
                    models.CharField(
                        choices=[
                            ("0", "I have never had a loan"),
                            ("1", "less than 6 months ago"),
                            ("2", "between 6 months and 2 years ago"),
                            ("3", "2 to 5 years ago"),
                            ("4", "5 to 10 years ago"),
                            ("5", "10 to 15 years ago"),
                            ("6", "more than 15 years ago"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Total_credit_limit", models.PositiveIntegerField()),
                ("Bankruptcy", models.BooleanField(default=False)),
                (
                    "credit_infor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
