# Generated by Django 4.1.7 on 2023-04-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FinCred", "0002_auto_20230417_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentinfor",
            name="employment_infor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
